services:
  sportfolio-proxy:
    image: nginx:latest
    container_name: sportfolio-proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/webserver.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/webroot
      - ./error:/var/www/error
  sportfolio-app:
    build:
      context: .
    container_name: sportfolio-app
    restart: unless-stopped
    command: npm run dev
    environment:
      - REDIS_CONNECT_STRING=redis://sportfolio-redis:6379/0
      - REDIS_SESSION_CONNECT_STRING=redis://sportfolio-redis:6379/1
      - MONGO_CONNECT_STRING=mongodb://sportfolio-mongo:27017
      - MONGO_DB_NAME=sportfolio
      - COOKIE_KEY=q1w2e3r4
      - SESSION_LENGTH=2147000
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - sportfolio-mongo
      - sportfolio-redis
  sportfolio-redis:
    container_name: sportfolio-redis
    restart: always
    image: redis:6.2.3
    volumes:
      - /opt/sportfolio-redis-data:/data
    ports:
      - 6379:6379
  sportfolio-mongo:
    container_name: sportfolio-mongo
    restart: always
    image: mongo:latest
    volumes:
      - /opt/sportfolio-mongo-data:/data/db
    ports:
      - 27017:27017
